# Action for build and deploy java project

name: Build java gradle project and Deploy to Azure Web App

env:
  azure-webapp-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5EA9A06C5E4E4147A4390F38C4B54723 }}
  azure-webapp-name: ${{ vars.AZURE_WEBAPP_API_NAME }}
  java-app-path: ${{ github.workspace }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  delete-artifacts:
    runs-on: ubuntu-latest
  
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts
          
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout to main branch'
      uses: actions/checkout@v3
      with:
        ref: main
    - name: 'Set up latest Oracle JDK 17'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 17
    - name: 'Setup Gradle'
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper #7.4 ver of project
    - name: 'Build Gradle'
      run: ./gradlew build -Dspring.profiles.active=mssql
    - name: 'Upload artifact of build'
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ env.java-app-path }}/build'
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: 'Download build artifact'
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: '${{ env.java-app-path }}/build/libs/*.jar'
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.azure-webapp-name }}
          publish-profile: ${{ env.azure-webapp-profile }}
